### ISSUE TITLE
Block names don't support inline script blocks.

### ISSUE THREAD

**Issue by SnaveSutit** [mc-build/mcb#14]
The following code
```
block some_<%'silly'%>_block {
  say Goofy ahh.
}
```
will attempt to write to a file called `some_<%'silly'%>_block` and fail, because that's not a valid file name.

I'd expect it to write to a file called `some_silly_block`

**Comment by SnaveSutit** [comment]
Looks like the macro arguments don't support them either...
```
![image](https://github.com/mc-build/mcb/assets/28514936/5e2efb1d-75b8-45b1-9350-dbc4b39ab60d)

![image](https://github.com/mc-build/mcb/assets/28514936/4d949fbb-8a96-4c62-a591-c0b69234b422)

**Comment by SnaveSutit** [comment]
Macro arguments still don't support inline blocks.
![image](https://github.com/mc-build/mcb/assets/28514936/b12c5a40-b55f-4f50-8e00-d63a4b081dd4)

**Comment by IanSSenne** [comment]
moved to #15
